version: "3.4"
services:
    client:
        image: react-app-starter:latest
        restart: always
        build: ./client
        ports:
            - "8080:8080"
        volumes:
            - ./usr/src/app
            - /usr/src/app/node_modules
        links:
            - server
    server:
        image: react-app-api:latest
        restart: always
        build: ./server
        ports:
            - "4000:4000"
        volumes:
            - ./api
            - /api/node_modules