version: "3.7"
services:
    client:
        image: react-app-starter:latest
        restart: always
        build: ./client
        ports:
            - "8080:8080"
        volumes: 
            - ./client:/usr/src/app/
        depends_on:
            - server
    server:
        image: react-app-api:latest
        restart: always
        build: ./server
        volumes: 
            - ./server:/usr/gql/
        ports:
            - "4000:4000"
